### ISSUE TITLE
不通过web 启动，单纯的使用exportor 会导致任务卡死

### ISSUE THREAD

**Issue by zhqqqy** [axiaoxin-com/x-stock#16]
**Describe the bug**
x-stock 不通过web 启动，单纯的使用exportor 会导致任务卡死,

**To Reproduce**
1. execute x-stock -l error exportor
2. See error，任务卡住

**Expected behavior**
应该导出excel 表格

**Screenshots**
![image](https://user-images.githubusercontent.com/13046318/129861229-180f3026-0678-40e0-b42d-348342f2e6f0.png)

**Desktop (please complete the following information):**
 - OS: [macos]
 - Version [x-stock version 1.2.19]

**Additional context**
排查问题是因为core/selector.go 第52行，
```go
workerCount := int(math.Min(float64(len(stocks)), float64(viper.GetFloat64("app.chan_size"))))
jobChan := make(chan struct{}, workerCount)
	wg := sync.WaitGroup{}
	var mu sync.Mutex

	for _, baseInfo := range stocks {
		wg.Add(1)
		jobChan <- struct{}{}

```
执行的函数中回去取toml 配置文件中的值，然后对比两个值之间的最小值.由于没有读到配置文件，导致 float64(viper.GetFloat64("app.chan_size")) 为默认值0 ，workerCount 为0 ，jobChan <- struct{}{} 这里就会被阻塞住整个函数。建议判断一下 workerCount 为0 的时候，设置为默认值

**Comment by axiaoxin** [comment]
感谢反馈，已修复  d85f3f1
