### ISSUE TITLE
怎么显示股票信息运行命令都是报错的

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [axiaoxin-com/x-stock#22]
![image](https://user-images.githubusercontent.com/28779327/132114046-daec2bef-1d81-4f3e-9e77-1551e2e3c59f.png)

**Comment by axiaoxin** [comment]
请问下是从release下载的吗？
我这里运行main分支最新代码是正常的
![2021-09-06_10-25](https://user-images.githubusercontent.com/2876405/132151869-c2e91f15-2bcf-4c25-90cb-7efdb5eba1be.png)

**Comment by wangwenqiangGitHub** [comment]
> 请问下是从release下载的吗？
> 我这里运行main分支最新代码是正常的
> ![2021-09-06_10-25](https://user-images.githubusercontent.com/2876405/132151869-c2e91f15-2bcf-4c25-90cb-7efdb5eba1be.png)

是用的最新的realease

**Comment by axiaoxin** [comment]
最近的提交没有发release 可以拉main自己编译

**Comment by wangwenqiangGitHub** [comment]
> 最近的提交没有发release 可以拉main自己编译

这个程序我太喜欢了，我熟悉一下代码，看看

**Comment by wangwenqiangGitHub** [comment]
主分支运行了一下，可以了
