### ISSUE TITLE
checker和exportor的输出结果及其判断的依据是什么？

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [axiaoxin-com/x-stock#23]
这个输出的股票，是什么判断依据，代表什么呢

**Comment by wangwenqiangGitHub** [comment]
go run . checker -k 比亚迪，为什么最后一项是报错failed，红色的字体代表不准确么

**Comment by axiaoxin** [comment]
> 这个输出的股票，是什么判断依据，代表什么呢

判断依据参考readme里面写的对优质标的的判断标准，输出结果代表满足那些条件的股票

**Comment by axiaoxin** [comment]
> go run . checker -k 比亚迪，为什么最后一项是报错failed，红色的字体代表不准确么

红色 failed代表存在不满足判断条件的判断标准

**Comment by wangwenqiangGitHub** [comment]
边读边测试这个代码，我在理解理解
